// Code generated by mkbuiltin.go. DO NOT EDIT.

package gc

import "cmd/compile/internal/types"

var runtimeDecls = [...]struct {
	name string
	tag  int
	typ  int
}{
	{"newobject", funcTag, 4},
	{"panicindex", funcTag, 5},
	{"panicslice", funcTag, 6},
	{"panicdivide", funcTag, 7},
	{"panicmakeslicelen", funcTag, 8},
	{"throwinit", funcTag, 9},
	{"panicwrap", funcTag, 10},
	{"gopanic", funcTag, 12},
	{"gorecover", funcTag, 15},
	{"goschedguarded", funcTag, 16},
	{"printbool", funcTag, 18},
	{"printfloat", funcTag, 20},
	{"printint", funcTag, 22},
	{"printhex", funcTag, 24},
	{"printuint", funcTag, 25},
	{"printcomplex", funcTag, 27},
	{"printstring", funcTag, 29},
	{"printpointer", funcTag, 30},
	{"printiface", funcTag, 31},
	{"printeface", funcTag, 32},
	{"printslice", funcTag, 33},
	{"printnl", funcTag, 34},
	{"printsp", funcTag, 35},
	{"printlock", funcTag, 36},
	{"printunlock", funcTag, 37},
	{"concatstring2", funcTag, 40},
	{"concatstring3", funcTag, 41},
	{"concatstring4", funcTag, 42},
	{"concatstring5", funcTag, 43},
	{"concatstrings", funcTag, 45},
	{"cmpstring", funcTag, 47},
	{"intstring", funcTag, 50},
	{"slicebytetostring", funcTag, 52},
	{"slicebytetostringtmp", funcTag, 53},
	{"slicerunetostring", funcTag, 56},
	{"stringtoslicebyte", funcTag, 57},
	{"stringtoslicerune", funcTag, 60},
	{"slicecopy", funcTag, 62},
	{"slicestringcopy", funcTag, 63},
	{"decoderune", funcTag, 64},
	{"countrunes", funcTag, 65},
	{"convI2I", funcTag, 66},
	{"convT2E", funcTag, 67},
	{"convT2E16", funcTag, 68},
	{"convT2E32", funcTag, 69},
	{"convT2E64", funcTag, 70},
	{"convT2Estring", funcTag, 71},
	{"convT2Eslice", funcTag, 72},
	{"convT2Enoptr", funcTag, 73},
	{"convT2I", funcTag, 74},
	{"convT2I16", funcTag, 75},
	{"convT2I32", funcTag, 76},
	{"convT2I64", funcTag, 77},
	{"convT2Istring", funcTag, 78},
	{"convT2Islice", funcTag, 79},
	{"convT2Inoptr", funcTag, 80},
	{"assertE2I", funcTag, 81},
	{"assertE2I2", funcTag, 82},
	{"assertI2I", funcTag, 83},
	{"assertI2I2", funcTag, 84},
	{"panicdottypeE", funcTag, 85},
	{"panicdottypeI", funcTag, 86},
	{"panicnildottype", funcTag, 87},
	{"ifaceeq", funcTag, 90},
	{"efaceeq", funcTag, 91},
	{"fastrand", funcTag, 93},
	{"makemap64", funcTag, 95},
	{"makemap", funcTag, 96},
	{"makemap_small", funcTag, 97},
	{"mapaccess1", funcTag, 98},
	{"mapaccess1_fast32", funcTag, 99},
	{"mapaccess1_fast64", funcTag, 100},
	{"mapaccess1_faststr", funcTag, 101},
	{"mapaccess1_fat", funcTag, 102},
	{"mapaccess2", funcTag, 103},
	{"mapaccess2_fast32", funcTag, 104},
	{"mapaccess2_fast64", funcTag, 105},
	{"mapaccess2_faststr", funcTag, 106},
	{"mapaccess2_fat", funcTag, 107},
	{"mapassign", funcTag, 108},
	{"mapassign_fast32", funcTag, 109},
	{"mapassign_fast32ptr", funcTag, 110},
	{"mapassign_fast64", funcTag, 111},
	{"mapassign_fast64ptr", funcTag, 112},
	{"mapassign_faststr", funcTag, 113},
	{"mapiterinit", funcTag, 114},
	{"mapdelete", funcTag, 115},
	{"mapdelete_fast32", funcTag, 116},
	{"mapdelete_fast64", funcTag, 117},
	{"mapdelete_faststr", funcTag, 118},
	{"mapiternext", funcTag, 119},
	{"mapclear", funcTag, 120},
	{"makechan64", funcTag, 122},
	{"makechan", funcTag, 123},
	{"chanrecv1", funcTag, 125},
	{"chanrecv2", funcTag, 126},
	{"chansend1", funcTag, 128},
	{"closechan", funcTag, 129},
	{"writeBarrier", varTag, 131},
	{"typedmemmove", funcTag, 132},
	{"typedmemclr", funcTag, 133},
	{"typedslicecopy", funcTag, 134},
	{"selectnbsend", funcTag, 135},
	{"selectnbrecv", funcTag, 136},
	{"selectnbrecv2", funcTag, 138},
	{"selectsetpc", funcTag, 139},
	{"selectgo", funcTag, 140},
	{"block", funcTag, 141},
	{"makeslice", funcTag, 142},
	{"makeslice64", funcTag, 143},
	{"growslice", funcTag, 145},
	{"memmove", funcTag, 146},
	{"memclrNoHeapPointers", funcTag, 147},
	{"memclrHasPointers", funcTag, 148},
	{"memequal", funcTag, 149},
	{"memequal8", funcTag, 150},
	{"memequal16", funcTag, 151},
	{"memequal32", funcTag, 152},
	{"memequal64", funcTag, 153},
	{"memequal128", funcTag, 154},
	{"int64div", funcTag, 155},
	{"uint64div", funcTag, 156},
	{"int64mod", funcTag, 157},
	{"uint64mod", funcTag, 158},
	{"float64toint64", funcTag, 159},
	{"float64touint64", funcTag, 160},
	{"float64touint32", funcTag, 161},
	{"int64tofloat64", funcTag, 162},
	{"uint64tofloat64", funcTag, 163},
	{"uint32tofloat64", funcTag, 164},
	{"complex128div", funcTag, 165},
	{"racefuncenter", funcTag, 166},
	{"racefuncenterfp", funcTag, 167},
	{"racefuncexit", funcTag, 168},
	{"raceread", funcTag, 169},
	{"racewrite", funcTag, 170},
	{"racereadrange", funcTag, 171},
	{"racewriterange", funcTag, 172},
	{"msanread", funcTag, 173},
	{"msanwrite", funcTag, 174},
	{"support_popcnt", varTag, 17},
	{"support_sse41", varTag, 17},
}

func runtimeTypes() []*types.Type {
	var typs [175]*types.Type
	typs[0] = types.Bytetype
	typs[1] = types.NewPtr(typs[0])
	typs[2] = types.Types[TANY]
	typs[3] = types.NewPtr(typs[2])
	typs[4] = functype(nil, []*Node{anonfield(typs[1])}, []*Node{anonfield(typs[3])})
	typs[5] = functype(nil, nil, nil)
	typs[6] = functype(nil, nil, nil)
	typs[7] = functype(nil, nil, nil)
	typs[8] = functype(nil, nil, nil)
	typs[9] = functype(nil, nil, nil)
	typs[10] = functype(nil, nil, nil)
	typs[11] = types.Types[TINTER]
	typs[12] = functype(nil, []*Node{anonfield(typs[11])}, nil)
	typs[13] = types.Types[TINT32]
	typs[14] = types.NewPtr(typs[13])
	typs[15] = functype(nil, []*Node{anonfield(typs[14])}, []*Node{anonfield(typs[11])})
	typs[16] = functype(nil, nil, nil)
	typs[17] = types.Types[TBOOL]
	typs[18] = functype(nil, []*Node{anonfield(typs[17])}, nil)
	typs[19] = types.Types[TFLOAT64]
	typs[20] = functype(nil, []*Node{anonfield(typs[19])}, nil)
	typs[21] = types.Types[TINT64]
	typs[22] = functype(nil, []*Node{anonfield(typs[21])}, nil)
	typs[23] = types.Types[TUINT64]
	typs[24] = functype(nil, []*Node{anonfield(typs[23])}, nil)
	typs[25] = functype(nil, []*Node{anonfield(typs[23])}, nil)
	typs[26] = types.Types[TCOMPLEX128]
	typs[27] = functype(nil, []*Node{anonfield(typs[26])}, nil)
	typs[28] = types.Types[TSTRING]
	typs[29] = functype(nil, []*Node{anonfield(typs[28])}, nil)
	typs[30] = functype(nil, []*Node{anonfield(typs[2])}, nil)
	typs[31] = functype(nil, []*Node{anonfield(typs[2])}, nil)
	typs[32] = functype(nil, []*Node{anonfield(typs[2])}, nil)
	typs[33] = functype(nil, []*Node{anonfield(typs[2])}, nil)
	typs[34] = functype(nil, nil, nil)
	typs[35] = functype(nil, nil, nil)
	typs[36] = functype(nil, nil, nil)
	typs[37] = functype(nil, nil, nil)
	typs[38] = types.NewArray(typs[0], 32)
	typs[39] = types.NewPtr(typs[38])
	typs[40] = functype(nil, []*Node{anonfield(typs[39]), anonfield(typs[28]), anonfield(typs[28])}, []*Node{anonfield(typs[28])})
	typs[41] = functype(nil, []*Node{anonfield(typs[39]), anonfield(typs[28]), anonfield(typs[28]), anonfield(typs[28])}, []*Node{anonfield(typs[28])})
	typs[42] = functype(nil, []*Node{anonfield(typs[39]), anonfield(typs[28]), anonfield(typs[28]), anonfield(typs[28]), anonfield(typs[28])}, []*Node{anonfield(typs[28])})
	typs[43] = functype(nil, []*Node{anonfield(typs[39]), anonfield(typs[28]), anonfield(typs[28]), anonfield(typs[28]), anonfield(typs[28]), anonfield(typs[28])}, []*Node{anonfield(typs[28])})
	typs[44] = types.NewSlice(typs[28])
	typs[45] = functype(nil, []*Node{anonfield(typs[39]), anonfield(typs[44])}, []*Node{anonfield(typs[28])})
	typs[46] = types.Types[TINT]
	typs[47] = functype(nil, []*Node{anonfield(typs[28]), anonfield(typs[28])}, []*Node{anonfield(typs[46])})
	typs[48] = types.NewArray(typs[0], 4)
	typs[49] = types.NewPtr(typs[48])
	typs[50] = functype(nil, []*Node{anonfield(typs[49]), anonfield(typs[21])}, []*Node{anonfield(typs[28])})
	typs[51] = types.NewSlice(typs[0])
	typs[52] = functype(nil, []*Node{anonfield(typs[39]), anonfield(typs[51])}, []*Node{anonfield(typs[28])})
	typs[53] = functype(nil, []*Node{anonfield(typs[51])}, []*Node{anonfield(typs[28])})
	typs[54] = types.Runetype
	typs[55] = types.NewSlice(typs[54])
	typs[56] = functype(nil, []*Node{anonfield(typs[39]), anonfield(typs[55])}, []*Node{anonfield(typs[28])})
	typs[57] = functype(nil, []*Node{anonfield(typs[39]), anonfield(typs[28])}, []*Node{anonfield(typs[51])})
	typs[58] = types.NewArray(typs[54], 32)
	typs[59] = types.NewPtr(typs[58])
	typs[60] = functype(nil, []*Node{anonfield(typs[59]), anonfield(typs[28])}, []*Node{anonfield(typs[55])})
	typs[61] = types.Types[TUINTPTR]
	typs[62] = functype(nil, []*Node{anonfield(typs[2]), anonfield(typs[2]), anonfield(typs[61])}, []*Node{anonfield(typs[46])})
	typs[63] = functype(nil, []*Node{anonfield(typs[2]), anonfield(typs[2])}, []*Node{anonfield(typs[46])})
	typs[64] = functype(nil, []*Node{anonfield(typs[28]), anonfield(typs[46])}, []*Node{anonfield(typs[54]), anonfield(typs[46])})
	typs[65] = functype(nil, []*Node{anonfield(typs[28])}, []*Node{anonfield(typs[46])})
	typs[66] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[67] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, []*Node{anonfield(typs[2])})
	typs[68] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[69] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[70] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[71] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[72] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[73] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, []*Node{anonfield(typs[2])})
	typs[74] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, []*Node{anonfield(typs[2])})
	typs[75] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[76] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[77] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[78] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[79] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[80] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, []*Node{anonfield(typs[2])})
	typs[81] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[82] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2]), anonfield(typs[17])})
	typs[83] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[84] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2]), anonfield(typs[17])})
	typs[85] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[1]), anonfield(typs[1])}, nil)
	typs[86] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[1]), anonfield(typs[1])}, nil)
	typs[87] = functype(nil, []*Node{anonfield(typs[1])}, nil)
	typs[88] = types.NewPtr(typs[61])
	typs[89] = types.Types[TUNSAFEPTR]
	typs[90] = functype(nil, []*Node{anonfield(typs[88]), anonfield(typs[89]), anonfield(typs[89])}, []*Node{anonfield(typs[17])})
	typs[91] = functype(nil, []*Node{anonfield(typs[88]), anonfield(typs[89]), anonfield(typs[89])}, []*Node{anonfield(typs[17])})
	typs[92] = types.Types[TUINT32]
	typs[93] = functype(nil, nil, []*Node{anonfield(typs[92])})
	typs[94] = types.NewMap(typs[2], typs[2])
	typs[95] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[21]), anonfield(typs[3])}, []*Node{anonfield(typs[94])})
	typs[96] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[46]), anonfield(typs[3])}, []*Node{anonfield(typs[94])})
	typs[97] = functype(nil, nil, []*Node{anonfield(typs[94])})
	typs[98] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[3])}, []*Node{anonfield(typs[3])})
	typs[99] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[100] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[101] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[102] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[3]), anonfield(typs[1])}, []*Node{anonfield(typs[3])})
	typs[103] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[3])}, []*Node{anonfield(typs[3]), anonfield(typs[17])})
	typs[104] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3]), anonfield(typs[17])})
	typs[105] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3]), anonfield(typs[17])})
	typs[106] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3]), anonfield(typs[17])})
	typs[107] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[3]), anonfield(typs[1])}, []*Node{anonfield(typs[3]), anonfield(typs[17])})
	typs[108] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[3])}, []*Node{anonfield(typs[3])})
	typs[109] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[110] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[111] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[112] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[113] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[114] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[3])}, nil)
	typs[115] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[3])}, nil)
	typs[116] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, nil)
	typs[117] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, nil)
	typs[118] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[2])}, nil)
	typs[119] = functype(nil, []*Node{anonfield(typs[3])}, nil)
	typs[120] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94])}, nil)
	typs[121] = types.NewChan(typs[2], types.Cboth)
	typs[122] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[21])}, []*Node{anonfield(typs[121])})
	typs[123] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[46])}, []*Node{anonfield(typs[121])})
	typs[124] = types.NewChan(typs[2], types.Crecv)
	typs[125] = functype(nil, []*Node{anonfield(typs[124]), anonfield(typs[3])}, nil)
	typs[126] = functype(nil, []*Node{anonfield(typs[124]), anonfield(typs[3])}, []*Node{anonfield(typs[17])})
	typs[127] = types.NewChan(typs[2], types.Csend)
	typs[128] = functype(nil, []*Node{anonfield(typs[127]), anonfield(typs[3])}, nil)
	typs[129] = functype(nil, []*Node{anonfield(typs[2])}, nil)
	typs[130] = types.NewArray(typs[0], 3)
	typs[131] = tostruct([]*Node{namedfield("enabled", typs[17]), namedfield("pad", typs[130]), namedfield("needed", typs[17]), namedfield("cgo", typs[17]), namedfield("alignme", typs[23])})
	typs[132] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3]), anonfield(typs[3])}, nil)
	typs[133] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, nil)
	typs[134] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2]), anonfield(typs[2])}, []*Node{anonfield(typs[46])})
	typs[135] = functype(nil, []*Node{anonfield(typs[127]), anonfield(typs[3])}, []*Node{anonfield(typs[17])})
	typs[136] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[124])}, []*Node{anonfield(typs[17])})
	typs[137] = types.NewPtr(typs[17])
	typs[138] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[137]), anonfield(typs[124])}, []*Node{anonfield(typs[17])})
	typs[139] = functype(nil, []*Node{anonfield(typs[1])}, nil)
	typs[140] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[1]), anonfield(typs[46])}, []*Node{anonfield(typs[46]), anonfield(typs[17])})
	typs[141] = functype(nil, nil, nil)
	typs[142] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[46]), anonfield(typs[46])}, []*Node{anonfield(typs[89])})
	typs[143] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[21]), anonfield(typs[21])}, []*Node{anonfield(typs[89])})
	typs[144] = types.NewSlice(typs[2])
	typs[145] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[144]), anonfield(typs[46])}, []*Node{anonfield(typs[144])})
	typs[146] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3]), anonfield(typs[61])}, nil)
	typs[147] = functype(nil, []*Node{anonfield(typs[89]), anonfield(typs[61])}, nil)
	typs[148] = functype(nil, []*Node{anonfield(typs[89]), anonfield(typs[61])}, nil)
	typs[149] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3]), anonfield(typs[61])}, []*Node{anonfield(typs[17])})
	typs[150] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3])}, []*Node{anonfield(typs[17])})
	typs[151] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3])}, []*Node{anonfield(typs[17])})
	typs[152] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3])}, []*Node{anonfield(typs[17])})
	typs[153] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3])}, []*Node{anonfield(typs[17])})
	typs[154] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3])}, []*Node{anonfield(typs[17])})
	typs[155] = functype(nil, []*Node{anonfield(typs[21]), anonfield(typs[21])}, []*Node{anonfield(typs[21])})
	typs[156] = functype(nil, []*Node{anonfield(typs[23]), anonfield(typs[23])}, []*Node{anonfield(typs[23])})
	typs[157] = functype(nil, []*Node{anonfield(typs[21]), anonfield(typs[21])}, []*Node{anonfield(typs[21])})
	typs[158] = functype(nil, []*Node{anonfield(typs[23]), anonfield(typs[23])}, []*Node{anonfield(typs[23])})
	typs[159] = functype(nil, []*Node{anonfield(typs[19])}, []*Node{anonfield(typs[21])})
	typs[160] = functype(nil, []*Node{anonfield(typs[19])}, []*Node{anonfield(typs[23])})
	typs[161] = functype(nil, []*Node{anonfield(typs[19])}, []*Node{anonfield(typs[92])})
	typs[162] = functype(nil, []*Node{anonfield(typs[21])}, []*Node{anonfield(typs[19])})
	typs[163] = functype(nil, []*Node{anonfield(typs[23])}, []*Node{anonfield(typs[19])})
	typs[164] = functype(nil, []*Node{anonfield(typs[92])}, []*Node{anonfield(typs[19])})
	typs[165] = functype(nil, []*Node{anonfield(typs[26]), anonfield(typs[26])}, []*Node{anonfield(typs[26])})
	typs[166] = functype(nil, []*Node{anonfield(typs[61])}, nil)
	typs[167] = functype(nil, nil, nil)
	typs[168] = functype(nil, nil, nil)
	typs[169] = functype(nil, []*Node{anonfield(typs[61])}, nil)
	typs[170] = functype(nil, []*Node{anonfield(typs[61])}, nil)
	typs[171] = functype(nil, []*Node{anonfield(typs[61]), anonfield(typs[61])}, nil)
	typs[172] = functype(nil, []*Node{anonfield(typs[61]), anonfield(typs[61])}, nil)
	typs[173] = functype(nil, []*Node{anonfield(typs[61]), anonfield(typs[61])}, nil)
	typs[174] = functype(nil, []*Node{anonfield(typs[61]), anonfield(typs[61])}, nil)
	return typs[:]
}
