// Code generated by mkbuiltin.go. DO NOT EDIT.

package gc

import "cmd/compile/internal/types"

var runtimeDecls = [...]struct {
	name string
	tag  int
	typ  int
}{
	{"newobject", funcTag, 4},
	{"newinterface", funcTag, 5},
	{"panicindex", funcTag, 6},
	{"panicslice", funcTag, 6},
	{"panicdivide", funcTag, 6},
	{"throwinit", funcTag, 6},
	{"panicwrap", funcTag, 6},
	{"gopanic", funcTag, 8},
	{"gorecover", funcTag, 11},
	{"goschedguarded", funcTag, 6},
	{"printbool", funcTag, 13},
	{"printfloat", funcTag, 15},
	{"printint", funcTag, 17},
	{"printhex", funcTag, 19},
	{"printuint", funcTag, 19},
	{"printcomplex", funcTag, 21},
	{"printstring", funcTag, 23},
	{"printpointer", funcTag, 24},
	{"printiface", funcTag, 24},
	{"printeface", funcTag, 24},
	{"printslice", funcTag, 24},
	{"printnl", funcTag, 6},
	{"printsp", funcTag, 6},
	{"printlock", funcTag, 6},
	{"printunlock", funcTag, 6},
	{"concatstring2", funcTag, 27},
	{"concatstring3", funcTag, 28},
	{"concatstring4", funcTag, 29},
	{"concatstring5", funcTag, 30},
	{"concatstrings", funcTag, 32},
	{"cmpstring", funcTag, 34},
	{"intstring", funcTag, 37},
	{"slicebytetostring", funcTag, 39},
	{"slicebytetostringtmp", funcTag, 40},
	{"slicerunetostring", funcTag, 43},
	{"stringtoslicebyte", funcTag, 44},
	{"stringtoslicerune", funcTag, 47},
	{"decoderune", funcTag, 48},
	{"slicecopy", funcTag, 50},
	{"slicestringcopy", funcTag, 51},
	{"convI2I", funcTag, 52},
	{"convT2E", funcTag, 53},
	{"convT2E16", funcTag, 53},
	{"convT2E32", funcTag, 53},
	{"convT2E64", funcTag, 53},
	{"convT2Estring", funcTag, 53},
	{"convT2Eslice", funcTag, 53},
	{"convT2Enoptr", funcTag, 53},
	{"convT2I", funcTag, 53},
	{"convT2I16", funcTag, 53},
	{"convT2I32", funcTag, 53},
	{"convT2I64", funcTag, 53},
	{"convT2Istring", funcTag, 53},
	{"convT2Islice", funcTag, 53},
	{"convT2Inoptr", funcTag, 53},
	{"assertE2I", funcTag, 52},
	{"assertE2I2", funcTag, 54},
	{"assertI2I", funcTag, 52},
	{"assertI2I2", funcTag, 54},
	{"panicdottypeE", funcTag, 55},
	{"panicdottypeI", funcTag, 55},
	{"panicnildottype", funcTag, 56},
	{"ifaceeq", funcTag, 59},
	{"efaceeq", funcTag, 59},
	{"fastrand", funcTag, 61},
	{"makemap64", funcTag, 63},
	{"makemap", funcTag, 64},
	{"makemap_small", funcTag, 65},
	{"mapaccess1", funcTag, 66},
	{"mapaccess1_fast32", funcTag, 67},
	{"mapaccess1_fast64", funcTag, 67},
	{"mapaccess1_faststr", funcTag, 67},
	{"mapaccess1_fat", funcTag, 68},
	{"mapaccess2", funcTag, 69},
	{"mapaccess2_fast32", funcTag, 70},
	{"mapaccess2_fast64", funcTag, 70},
	{"mapaccess2_faststr", funcTag, 70},
	{"mapaccess2_fat", funcTag, 71},
	{"mapassign", funcTag, 66},
	{"mapassign_fast32", funcTag, 67},
	{"mapassign_fast32ptr", funcTag, 67},
	{"mapassign_fast64", funcTag, 67},
	{"mapassign_fast64ptr", funcTag, 67},
	{"mapassign_faststr", funcTag, 67},
	{"mapiterinit", funcTag, 72},
	{"mapdelete", funcTag, 72},
	{"mapdelete_fast32", funcTag, 73},
	{"mapdelete_fast64", funcTag, 73},
	{"mapdelete_faststr", funcTag, 73},
	{"mapiternext", funcTag, 74},
	{"makechan64", funcTag, 76},
	{"makechan", funcTag, 77},
	{"chanrecv1", funcTag, 79},
	{"chanrecv2", funcTag, 80},
	{"chansend1", funcTag, 82},
	{"closechan", funcTag, 24},
	{"writeBarrier", varTag, 84},
	{"typedmemmove", funcTag, 85},
	{"typedmemclr", funcTag, 86},
	{"typedslicecopy", funcTag, 87},
	{"selectnbsend", funcTag, 88},
	{"selectnbrecv", funcTag, 89},
	{"selectnbrecv2", funcTag, 91},
	{"newselect", funcTag, 92},
	{"selectsend", funcTag, 93},
	{"selectrecv", funcTag, 94},
	{"selectdefault", funcTag, 56},
	{"selectgo", funcTag, 95},
	{"block", funcTag, 6},
	{"makeslice", funcTag, 97},
	{"makeslice64", funcTag, 98},
	{"growslice", funcTag, 99},
	{"memmove", funcTag, 100},
	{"memclrNoHeapPointers", funcTag, 101},
	{"memclrHasPointers", funcTag, 101},
	{"memequal", funcTag, 102},
	{"memequal8", funcTag, 103},
	{"memequal16", funcTag, 103},
	{"memequal32", funcTag, 103},
	{"memequal64", funcTag, 103},
	{"memequal128", funcTag, 103},
	{"int64div", funcTag, 104},
	{"uint64div", funcTag, 105},
	{"int64mod", funcTag, 104},
	{"uint64mod", funcTag, 105},
	{"float64toint64", funcTag, 106},
	{"float64touint64", funcTag, 107},
	{"float64touint32", funcTag, 108},
	{"int64tofloat64", funcTag, 109},
	{"uint64tofloat64", funcTag, 110},
	{"uint32tofloat64", funcTag, 111},
	{"complex128div", funcTag, 112},
	{"racefuncenter", funcTag, 113},
	{"racefuncexit", funcTag, 6},
	{"raceread", funcTag, 113},
	{"racewrite", funcTag, 113},
	{"racereadrange", funcTag, 114},
	{"racewriterange", funcTag, 114},
	{"msanread", funcTag, 114},
	{"msanwrite", funcTag, 114},
	{"support_popcnt", varTag, 12},
	{"support_sse41", varTag, 12},
}

func runtimeTypes() []*types.Type {
	var typs [115]*types.Type
	typs[0] = types.Bytetype
	typs[1] = types.NewPtr(typs[0])
	typs[2] = types.Types[TANY]
	typs[3] = types.NewPtr(typs[2])
	typs[4] = functype(nil, []*Node{anonfield(typs[1])}, []*Node{anonfield(typs[3])})
	typs[5] = functype(nil, nil, []*Node{anonfield(typs[3])})
	typs[6] = functype(nil, nil, nil)
	typs[7] = types.Types[TINTER]
	typs[8] = functype(nil, []*Node{anonfield(typs[7])}, nil)
	typs[9] = types.Types[TINT32]
	typs[10] = types.NewPtr(typs[9])
	typs[11] = functype(nil, []*Node{anonfield(typs[10])}, []*Node{anonfield(typs[7])})
	typs[12] = types.Types[TBOOL]
	typs[13] = functype(nil, []*Node{anonfield(typs[12])}, nil)
	typs[14] = types.Types[TFLOAT64]
	typs[15] = functype(nil, []*Node{anonfield(typs[14])}, nil)
	typs[16] = types.Types[TINT64]
	typs[17] = functype(nil, []*Node{anonfield(typs[16])}, nil)
	typs[18] = types.Types[TUINT64]
	typs[19] = functype(nil, []*Node{anonfield(typs[18])}, nil)
	typs[20] = types.Types[TCOMPLEX128]
	typs[21] = functype(nil, []*Node{anonfield(typs[20])}, nil)
	typs[22] = types.Types[TSTRING]
	typs[23] = functype(nil, []*Node{anonfield(typs[22])}, nil)
	typs[24] = functype(nil, []*Node{anonfield(typs[2])}, nil)
	typs[25] = types.NewArray(typs[0], 32)
	typs[26] = types.NewPtr(typs[25])
	typs[27] = functype(nil, []*Node{anonfield(typs[26]), anonfield(typs[22]), anonfield(typs[22])}, []*Node{anonfield(typs[22])})
	typs[28] = functype(nil, []*Node{anonfield(typs[26]), anonfield(typs[22]), anonfield(typs[22]), anonfield(typs[22])}, []*Node{anonfield(typs[22])})
	typs[29] = functype(nil, []*Node{anonfield(typs[26]), anonfield(typs[22]), anonfield(typs[22]), anonfield(typs[22]), anonfield(typs[22])}, []*Node{anonfield(typs[22])})
	typs[30] = functype(nil, []*Node{anonfield(typs[26]), anonfield(typs[22]), anonfield(typs[22]), anonfield(typs[22]), anonfield(typs[22]), anonfield(typs[22])}, []*Node{anonfield(typs[22])})
	typs[31] = types.NewSlice(typs[22])
	typs[32] = functype(nil, []*Node{anonfield(typs[26]), anonfield(typs[31])}, []*Node{anonfield(typs[22])})
	typs[33] = types.Types[TINT]
	typs[34] = functype(nil, []*Node{anonfield(typs[22]), anonfield(typs[22])}, []*Node{anonfield(typs[33])})
	typs[35] = types.NewArray(typs[0], 4)
	typs[36] = types.NewPtr(typs[35])
	typs[37] = functype(nil, []*Node{anonfield(typs[36]), anonfield(typs[16])}, []*Node{anonfield(typs[22])})
	typs[38] = types.NewSlice(typs[0])
	typs[39] = functype(nil, []*Node{anonfield(typs[26]), anonfield(typs[38])}, []*Node{anonfield(typs[22])})
	typs[40] = functype(nil, []*Node{anonfield(typs[38])}, []*Node{anonfield(typs[22])})
	typs[41] = types.Runetype
	typs[42] = types.NewSlice(typs[41])
	typs[43] = functype(nil, []*Node{anonfield(typs[26]), anonfield(typs[42])}, []*Node{anonfield(typs[22])})
	typs[44] = functype(nil, []*Node{anonfield(typs[26]), anonfield(typs[22])}, []*Node{anonfield(typs[38])})
	typs[45] = types.NewArray(typs[41], 32)
	typs[46] = types.NewPtr(typs[45])
	typs[47] = functype(nil, []*Node{anonfield(typs[46]), anonfield(typs[22])}, []*Node{anonfield(typs[42])})
	typs[48] = functype(nil, []*Node{anonfield(typs[22]), anonfield(typs[33])}, []*Node{anonfield(typs[41]), anonfield(typs[33])})
	typs[49] = types.Types[TUINTPTR]
	typs[50] = functype(nil, []*Node{anonfield(typs[2]), anonfield(typs[2]), anonfield(typs[49])}, []*Node{anonfield(typs[33])})
	typs[51] = functype(nil, []*Node{anonfield(typs[2]), anonfield(typs[2])}, []*Node{anonfield(typs[33])})
	typs[52] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[53] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, []*Node{anonfield(typs[2])})
	typs[54] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2]), anonfield(typs[12])})
	typs[55] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[1]), anonfield(typs[1])}, nil)
	typs[56] = functype(nil, []*Node{anonfield(typs[1])}, nil)
	typs[57] = types.NewPtr(typs[49])
	typs[58] = types.Types[TUNSAFEPTR]
	typs[59] = functype(nil, []*Node{anonfield(typs[57]), anonfield(typs[58]), anonfield(typs[58])}, []*Node{anonfield(typs[12])})
	typs[60] = types.Types[TUINT32]
	typs[61] = functype(nil, nil, []*Node{anonfield(typs[60])})
	typs[62] = types.NewMap(typs[2], typs[2])
	typs[63] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[16]), anonfield(typs[3])}, []*Node{anonfield(typs[62])})
	typs[64] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[33]), anonfield(typs[3])}, []*Node{anonfield(typs[62])})
	typs[65] = functype(nil, nil, []*Node{anonfield(typs[62])})
	typs[66] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[3])}, []*Node{anonfield(typs[3])})
	typs[67] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[68] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[3]), anonfield(typs[1])}, []*Node{anonfield(typs[3])})
	typs[69] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[3])}, []*Node{anonfield(typs[3]), anonfield(typs[12])})
	typs[70] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[2])}, []*Node{anonfield(typs[3]), anonfield(typs[12])})
	typs[71] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[3]), anonfield(typs[1])}, []*Node{anonfield(typs[3]), anonfield(typs[12])})
	typs[72] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[3])}, nil)
	typs[73] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[2])}, nil)
	typs[74] = functype(nil, []*Node{anonfield(typs[3])}, nil)
	typs[75] = types.NewChan(typs[2], types.Cboth)
	typs[76] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[16])}, []*Node{anonfield(typs[75])})
	typs[77] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[33])}, []*Node{anonfield(typs[75])})
	typs[78] = types.NewChan(typs[2], types.Crecv)
	typs[79] = functype(nil, []*Node{anonfield(typs[78]), anonfield(typs[3])}, nil)
	typs[80] = functype(nil, []*Node{anonfield(typs[78]), anonfield(typs[3])}, []*Node{anonfield(typs[12])})
	typs[81] = types.NewChan(typs[2], types.Csend)
	typs[82] = functype(nil, []*Node{anonfield(typs[81]), anonfield(typs[3])}, nil)
	typs[83] = types.NewArray(typs[0], 3)
	typs[84] = tostruct([]*Node{namedfield("enabled", typs[12]), namedfield("pad", typs[83]), namedfield("needed", typs[12]), namedfield("cgo", typs[12]), namedfield("alignme", typs[18])})
	typs[85] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3]), anonfield(typs[3])}, nil)
	typs[86] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, nil)
	typs[87] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2]), anonfield(typs[2])}, []*Node{anonfield(typs[33])})
	typs[88] = functype(nil, []*Node{anonfield(typs[81]), anonfield(typs[3])}, []*Node{anonfield(typs[12])})
	typs[89] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[78])}, []*Node{anonfield(typs[12])})
	typs[90] = types.NewPtr(typs[12])
	typs[91] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[90]), anonfield(typs[78])}, []*Node{anonfield(typs[12])})
	typs[92] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[16]), anonfield(typs[9])}, nil)
	typs[93] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[81]), anonfield(typs[3])}, nil)
	typs[94] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[78]), anonfield(typs[3]), anonfield(typs[90])}, nil)
	typs[95] = functype(nil, []*Node{anonfield(typs[1])}, []*Node{anonfield(typs[33])})
	typs[96] = types.NewSlice(typs[2])
	typs[97] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[33]), anonfield(typs[33])}, []*Node{anonfield(typs[96])})
	typs[98] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[16]), anonfield(typs[16])}, []*Node{anonfield(typs[96])})
	typs[99] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[96]), anonfield(typs[33])}, []*Node{anonfield(typs[96])})
	typs[100] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3]), anonfield(typs[49])}, nil)
	typs[101] = functype(nil, []*Node{anonfield(typs[58]), anonfield(typs[49])}, nil)
	typs[102] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3]), anonfield(typs[49])}, []*Node{anonfield(typs[12])})
	typs[103] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3])}, []*Node{anonfield(typs[12])})
	typs[104] = functype(nil, []*Node{anonfield(typs[16]), anonfield(typs[16])}, []*Node{anonfield(typs[16])})
	typs[105] = functype(nil, []*Node{anonfield(typs[18]), anonfield(typs[18])}, []*Node{anonfield(typs[18])})
	typs[106] = functype(nil, []*Node{anonfield(typs[14])}, []*Node{anonfield(typs[16])})
	typs[107] = functype(nil, []*Node{anonfield(typs[14])}, []*Node{anonfield(typs[18])})
	typs[108] = functype(nil, []*Node{anonfield(typs[14])}, []*Node{anonfield(typs[60])})
	typs[109] = functype(nil, []*Node{anonfield(typs[16])}, []*Node{anonfield(typs[14])})
	typs[110] = functype(nil, []*Node{anonfield(typs[18])}, []*Node{anonfield(typs[14])})
	typs[111] = functype(nil, []*Node{anonfield(typs[60])}, []*Node{anonfield(typs[14])})
	typs[112] = functype(nil, []*Node{anonfield(typs[20]), anonfield(typs[20])}, []*Node{anonfield(typs[20])})
	typs[113] = functype(nil, []*Node{anonfield(typs[49])}, nil)
	typs[114] = functype(nil, []*Node{anonfield(typs[49]), anonfield(typs[49])}, nil)
	return typs[:]
}
