// Code generated by mkbuiltin.go. DO NOT EDIT.

package gc

import "cmd/compile/internal/types"

var runtimeDecls = [...]struct {
	name string
	tag  int
	typ  int
}{
	{"newobject", funcTag, 4},
	{"rawmem", funcTag, 8},
	{"panicindex", funcTag, 9},
	{"panicslice", funcTag, 9},
	{"panicdivide", funcTag, 9},
	{"throwinit", funcTag, 9},
	{"panicwrap", funcTag, 9},
	{"gopanic", funcTag, 11},
	{"gorecover", funcTag, 14},
	{"goschedguarded", funcTag, 9},
	{"printbool", funcTag, 16},
	{"printfloat", funcTag, 18},
	{"printint", funcTag, 20},
	{"printhex", funcTag, 22},
	{"printuint", funcTag, 22},
	{"printcomplex", funcTag, 24},
	{"printstring", funcTag, 26},
	{"printpointer", funcTag, 27},
	{"printiface", funcTag, 27},
	{"printeface", funcTag, 27},
	{"printslice", funcTag, 27},
	{"printnl", funcTag, 9},
	{"printsp", funcTag, 9},
	{"printlock", funcTag, 9},
	{"printunlock", funcTag, 9},
	{"concatstring2", funcTag, 30},
	{"concatstring3", funcTag, 31},
	{"concatstring4", funcTag, 32},
	{"concatstring5", funcTag, 33},
	{"concatstrings", funcTag, 35},
	{"cmpstring", funcTag, 37},
	{"intstring", funcTag, 40},
	{"slicebytetostring", funcTag, 42},
	{"slicebytetostringtmp", funcTag, 43},
	{"slicerunetostring", funcTag, 46},
	{"stringtoslicebyte", funcTag, 47},
	{"stringtoslicerune", funcTag, 50},
	{"decoderune", funcTag, 51},
	{"slicecopy", funcTag, 52},
	{"slicestringcopy", funcTag, 53},
	{"convI2I", funcTag, 54},
	{"convT2E", funcTag, 55},
	{"convT2E16", funcTag, 55},
	{"convT2E32", funcTag, 55},
	{"convT2E64", funcTag, 55},
	{"convT2Estring", funcTag, 55},
	{"convT2Eslice", funcTag, 55},
	{"convT2Enoptr", funcTag, 55},
	{"convT2I", funcTag, 55},
	{"convT2I16", funcTag, 55},
	{"convT2I32", funcTag, 55},
	{"convT2I64", funcTag, 55},
	{"convT2Istring", funcTag, 55},
	{"convT2Islice", funcTag, 55},
	{"convT2Inoptr", funcTag, 55},
	{"assertE2I", funcTag, 54},
	{"assertE2I2", funcTag, 56},
	{"assertI2I", funcTag, 54},
	{"assertI2I2", funcTag, 56},
	{"panicdottypeE", funcTag, 57},
	{"panicdottypeI", funcTag, 57},
	{"panicnildottype", funcTag, 58},
	{"ifaceeq", funcTag, 61},
	{"efaceeq", funcTag, 61},
	{"fastrand", funcTag, 63},
	{"makemap64", funcTag, 65},
	{"makemap", funcTag, 66},
	{"makemap_small", funcTag, 67},
	{"mapaccess1", funcTag, 68},
	{"mapaccess1_fast32", funcTag, 69},
	{"mapaccess1_fast64", funcTag, 69},
	{"mapaccess1_faststr", funcTag, 69},
	{"mapaccess1_fat", funcTag, 70},
	{"mapaccess2", funcTag, 71},
	{"mapaccess2_fast32", funcTag, 72},
	{"mapaccess2_fast64", funcTag, 72},
	{"mapaccess2_faststr", funcTag, 72},
	{"mapaccess2_fat", funcTag, 73},
	{"mapassign", funcTag, 68},
	{"mapassign_fast32", funcTag, 69},
	{"mapassign_fast32ptr", funcTag, 69},
	{"mapassign_fast64", funcTag, 69},
	{"mapassign_fast64ptr", funcTag, 69},
	{"mapassign_faststr", funcTag, 69},
	{"mapiterinit", funcTag, 74},
	{"mapdelete", funcTag, 74},
	{"mapdelete_fast32", funcTag, 75},
	{"mapdelete_fast64", funcTag, 75},
	{"mapdelete_faststr", funcTag, 75},
	{"mapiternext", funcTag, 76},
	{"makechan64", funcTag, 78},
	{"makechan", funcTag, 79},
	{"chanrecv1", funcTag, 81},
	{"chanrecv2", funcTag, 82},
	{"chansend1", funcTag, 84},
	{"closechan", funcTag, 27},
	{"writeBarrier", varTag, 86},
	{"typedmemmove", funcTag, 87},
	{"typedmemclr", funcTag, 88},
	{"typedslicecopy", funcTag, 89},
	{"selectnbsend", funcTag, 90},
	{"selectnbrecv", funcTag, 91},
	{"selectnbrecv2", funcTag, 93},
	{"newselect", funcTag, 94},
	{"selectsend", funcTag, 95},
	{"selectrecv", funcTag, 96},
	{"selectdefault", funcTag, 58},
	{"selectgo", funcTag, 97},
	{"block", funcTag, 9},
	{"makeslice", funcTag, 99},
	{"makeslice64", funcTag, 100},
	{"growslice", funcTag, 101},
	{"memmove", funcTag, 102},
	{"memclrNoHeapPointers", funcTag, 103},
	{"memclrHasPointers", funcTag, 103},
	{"memequal", funcTag, 104},
	{"memequal8", funcTag, 105},
	{"memequal16", funcTag, 105},
	{"memequal32", funcTag, 105},
	{"memequal64", funcTag, 105},
	{"memequal128", funcTag, 105},
	{"int64div", funcTag, 106},
	{"uint64div", funcTag, 107},
	{"int64mod", funcTag, 106},
	{"uint64mod", funcTag, 107},
	{"float64toint64", funcTag, 108},
	{"float64touint64", funcTag, 109},
	{"float64touint32", funcTag, 110},
	{"int64tofloat64", funcTag, 111},
	{"uint64tofloat64", funcTag, 112},
	{"uint32tofloat64", funcTag, 113},
	{"complex128div", funcTag, 114},
	{"racefuncenter", funcTag, 115},
	{"racefuncexit", funcTag, 9},
	{"raceread", funcTag, 115},
	{"racewrite", funcTag, 115},
	{"racereadrange", funcTag, 116},
	{"racewriterange", funcTag, 116},
	{"msanread", funcTag, 116},
	{"msanwrite", funcTag, 116},
	{"support_popcnt", varTag, 15},
	{"support_sse41", varTag, 15},
}

func runtimeTypes() []*types.Type {
	var typs [117]*types.Type
	typs[0] = types.Bytetype
	typs[1] = types.NewPtr(typs[0])
	typs[2] = types.Types[TANY]
	typs[3] = types.NewPtr(typs[2])
	typs[4] = functype(nil, []*Node{anonfield(typs[1])}, []*Node{anonfield(typs[3])})
	typs[5] = types.Types[TUINTPTR]
	typs[6] = types.Types[TUINT8]
	typs[7] = types.NewPtr(typs[6])
	typs[8] = functype(nil, []*Node{anonfield(typs[5])}, []*Node{anonfield(typs[7])})
	typs[9] = functype(nil, nil, nil)
	typs[10] = types.Types[TINTER]
	typs[11] = functype(nil, []*Node{anonfield(typs[10])}, nil)
	typs[12] = types.Types[TINT32]
	typs[13] = types.NewPtr(typs[12])
	typs[14] = functype(nil, []*Node{anonfield(typs[13])}, []*Node{anonfield(typs[10])})
	typs[15] = types.Types[TBOOL]
	typs[16] = functype(nil, []*Node{anonfield(typs[15])}, nil)
	typs[17] = types.Types[TFLOAT64]
	typs[18] = functype(nil, []*Node{anonfield(typs[17])}, nil)
	typs[19] = types.Types[TINT64]
	typs[20] = functype(nil, []*Node{anonfield(typs[19])}, nil)
	typs[21] = types.Types[TUINT64]
	typs[22] = functype(nil, []*Node{anonfield(typs[21])}, nil)
	typs[23] = types.Types[TCOMPLEX128]
	typs[24] = functype(nil, []*Node{anonfield(typs[23])}, nil)
	typs[25] = types.Types[TSTRING]
	typs[26] = functype(nil, []*Node{anonfield(typs[25])}, nil)
	typs[27] = functype(nil, []*Node{anonfield(typs[2])}, nil)
	typs[28] = types.NewArray(typs[0], 32)
	typs[29] = types.NewPtr(typs[28])
	typs[30] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[25]), anonfield(typs[25])}, []*Node{anonfield(typs[25])})
	typs[31] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25])}, []*Node{anonfield(typs[25])})
	typs[32] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25])}, []*Node{anonfield(typs[25])})
	typs[33] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25])}, []*Node{anonfield(typs[25])})
	typs[34] = types.NewSlice(typs[25])
	typs[35] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[34])}, []*Node{anonfield(typs[25])})
	typs[36] = types.Types[TINT]
	typs[37] = functype(nil, []*Node{anonfield(typs[25]), anonfield(typs[25])}, []*Node{anonfield(typs[36])})
	typs[38] = types.NewArray(typs[0], 4)
	typs[39] = types.NewPtr(typs[38])
	typs[40] = functype(nil, []*Node{anonfield(typs[39]), anonfield(typs[19])}, []*Node{anonfield(typs[25])})
	typs[41] = types.NewSlice(typs[0])
	typs[42] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[41])}, []*Node{anonfield(typs[25])})
	typs[43] = functype(nil, []*Node{anonfield(typs[41])}, []*Node{anonfield(typs[25])})
	typs[44] = types.Runetype
	typs[45] = types.NewSlice(typs[44])
	typs[46] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[45])}, []*Node{anonfield(typs[25])})
	typs[47] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[25])}, []*Node{anonfield(typs[41])})
	typs[48] = types.NewArray(typs[44], 32)
	typs[49] = types.NewPtr(typs[48])
	typs[50] = functype(nil, []*Node{anonfield(typs[49]), anonfield(typs[25])}, []*Node{anonfield(typs[45])})
	typs[51] = functype(nil, []*Node{anonfield(typs[25]), anonfield(typs[36])}, []*Node{anonfield(typs[44]), anonfield(typs[36])})
	typs[52] = functype(nil, []*Node{anonfield(typs[2]), anonfield(typs[2]), anonfield(typs[5])}, []*Node{anonfield(typs[36])})
	typs[53] = functype(nil, []*Node{anonfield(typs[2]), anonfield(typs[2])}, []*Node{anonfield(typs[36])})
	typs[54] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[55] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, []*Node{anonfield(typs[2])})
	typs[56] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2]), anonfield(typs[15])})
	typs[57] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[1]), anonfield(typs[1])}, nil)
	typs[58] = functype(nil, []*Node{anonfield(typs[1])}, nil)
	typs[59] = types.NewPtr(typs[5])
	typs[60] = types.Types[TUNSAFEPTR]
	typs[61] = functype(nil, []*Node{anonfield(typs[59]), anonfield(typs[60]), anonfield(typs[60])}, []*Node{anonfield(typs[15])})
	typs[62] = types.Types[TUINT32]
	typs[63] = functype(nil, nil, []*Node{anonfield(typs[62])})
	typs[64] = types.NewMap(typs[2], typs[2])
	typs[65] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[19]), anonfield(typs[3])}, []*Node{anonfield(typs[64])})
	typs[66] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[36]), anonfield(typs[3])}, []*Node{anonfield(typs[64])})
	typs[67] = functype(nil, nil, []*Node{anonfield(typs[64])})
	typs[68] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[64]), anonfield(typs[3])}, []*Node{anonfield(typs[3])})
	typs[69] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[64]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[70] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[64]), anonfield(typs[3]), anonfield(typs[1])}, []*Node{anonfield(typs[3])})
	typs[71] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[64]), anonfield(typs[3])}, []*Node{anonfield(typs[3]), anonfield(typs[15])})
	typs[72] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[64]), anonfield(typs[2])}, []*Node{anonfield(typs[3]), anonfield(typs[15])})
	typs[73] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[64]), anonfield(typs[3]), anonfield(typs[1])}, []*Node{anonfield(typs[3]), anonfield(typs[15])})
	typs[74] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[64]), anonfield(typs[3])}, nil)
	typs[75] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[64]), anonfield(typs[2])}, nil)
	typs[76] = functype(nil, []*Node{anonfield(typs[3])}, nil)
	typs[77] = types.NewChan(typs[2], types.Cboth)
	typs[78] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[19])}, []*Node{anonfield(typs[77])})
	typs[79] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[36])}, []*Node{anonfield(typs[77])})
	typs[80] = types.NewChan(typs[2], types.Crecv)
	typs[81] = functype(nil, []*Node{anonfield(typs[80]), anonfield(typs[3])}, nil)
	typs[82] = functype(nil, []*Node{anonfield(typs[80]), anonfield(typs[3])}, []*Node{anonfield(typs[15])})
	typs[83] = types.NewChan(typs[2], types.Csend)
	typs[84] = functype(nil, []*Node{anonfield(typs[83]), anonfield(typs[3])}, nil)
	typs[85] = types.NewArray(typs[0], 3)
	typs[86] = tostruct([]*Node{namedfield("enabled", typs[15]), namedfield("pad", typs[85]), namedfield("needed", typs[15]), namedfield("cgo", typs[15]), namedfield("alignme", typs[21])})
	typs[87] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3]), anonfield(typs[3])}, nil)
	typs[88] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, nil)
	typs[89] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2]), anonfield(typs[2])}, []*Node{anonfield(typs[36])})
	typs[90] = functype(nil, []*Node{anonfield(typs[83]), anonfield(typs[3])}, []*Node{anonfield(typs[15])})
	typs[91] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[80])}, []*Node{anonfield(typs[15])})
	typs[92] = types.NewPtr(typs[15])
	typs[93] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[92]), anonfield(typs[80])}, []*Node{anonfield(typs[15])})
	typs[94] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[19]), anonfield(typs[12])}, nil)
	typs[95] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[83]), anonfield(typs[3])}, nil)
	typs[96] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[80]), anonfield(typs[3]), anonfield(typs[92])}, nil)
	typs[97] = functype(nil, []*Node{anonfield(typs[1])}, []*Node{anonfield(typs[36])})
	typs[98] = types.NewSlice(typs[2])
	typs[99] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[36]), anonfield(typs[36])}, []*Node{anonfield(typs[98])})
	typs[100] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[19]), anonfield(typs[19])}, []*Node{anonfield(typs[98])})
	typs[101] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[98]), anonfield(typs[36])}, []*Node{anonfield(typs[98])})
	typs[102] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3]), anonfield(typs[5])}, nil)
	typs[103] = functype(nil, []*Node{anonfield(typs[60]), anonfield(typs[5])}, nil)
	typs[104] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3]), anonfield(typs[5])}, []*Node{anonfield(typs[15])})
	typs[105] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3])}, []*Node{anonfield(typs[15])})
	typs[106] = functype(nil, []*Node{anonfield(typs[19]), anonfield(typs[19])}, []*Node{anonfield(typs[19])})
	typs[107] = functype(nil, []*Node{anonfield(typs[21]), anonfield(typs[21])}, []*Node{anonfield(typs[21])})
	typs[108] = functype(nil, []*Node{anonfield(typs[17])}, []*Node{anonfield(typs[19])})
	typs[109] = functype(nil, []*Node{anonfield(typs[17])}, []*Node{anonfield(typs[21])})
	typs[110] = functype(nil, []*Node{anonfield(typs[17])}, []*Node{anonfield(typs[62])})
	typs[111] = functype(nil, []*Node{anonfield(typs[19])}, []*Node{anonfield(typs[17])})
	typs[112] = functype(nil, []*Node{anonfield(typs[21])}, []*Node{anonfield(typs[17])})
	typs[113] = functype(nil, []*Node{anonfield(typs[62])}, []*Node{anonfield(typs[17])})
	typs[114] = functype(nil, []*Node{anonfield(typs[23]), anonfield(typs[23])}, []*Node{anonfield(typs[23])})
	typs[115] = functype(nil, []*Node{anonfield(typs[5])}, nil)
	typs[116] = functype(nil, []*Node{anonfield(typs[5]), anonfield(typs[5])}, nil)
	return typs[:]
}
